DEBUG 2018-03-07 14:11:03,664: 	 Executing command: 'resubmit'
DEBUG 2018-03-07 14:11:03,664: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-07 14:11:03,666: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-07 14:11:03,666: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-07 14:11:04,093: 	 Executing command: 'resubmit'
DEBUG 2018-03-07 14:11:04,093: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-07 14:11:04,095: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-07 14:11:04,095: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-07 15:59:09,003: 	 Executing command: 'resubmit'
DEBUG 2018-03-07 15:59:09,004: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-07 15:59:09,005: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-07 15:59:09,005: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-07 15:59:09,409: 	 Executing command: 'resubmit'
DEBUG 2018-03-07 15:59:09,409: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-07 15:59:09,410: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-07 15:59:09,410: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-08 02:29:42,374: 	 Executing command: 'resubmit'
DEBUG 2018-03-08 02:29:42,375: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-08 02:29:42,377: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-08 02:29:42,377: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-08 02:29:43,105: 	 Executing command: 'resubmit'
DEBUG 2018-03-08 02:29:43,105: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-08 02:29:43,108: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-08 02:29:43,108: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-08 08:36:04,536: 	 Executing command: 'resubmit'
DEBUG 2018-03-08 08:36:04,536: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-08 08:36:04,538: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-08 08:36:04,538: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-08 08:36:05,255: 	 Executing command: 'resubmit'
DEBUG 2018-03-08 08:36:05,256: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-08 08:36:05,257: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-08 08:36:05,258: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-08 10:40:19,941: 	 Executing command: 'resubmit'
DEBUG 2018-03-08 10:40:19,941: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-08 10:40:19,951: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-08 10:40:19,951: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-08 10:40:20,721: 	 Executing command: 'resubmit'
DEBUG 2018-03-08 10:40:20,722: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-08 10:40:20,724: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-08 10:40:20,724: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-08 11:27:49,797: 	 Executing command: 'resubmit'
DEBUG 2018-03-08 11:27:49,797: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-08 11:27:49,800: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-08 11:27:49,800: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-08 11:27:50,518: 	 Executing command: 'resubmit'
DEBUG 2018-03-08 11:27:50,518: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-08 11:27:50,520: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-08 11:27:50,520: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-09 05:09:06,188: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 05:09:06,188: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 05:09:06,190: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-09 05:09:06,190: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-09 05:09:06,792: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 05:09:06,792: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 05:09:06,794: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-09 05:09:06,794: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-09 07:22:18,949: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 07:22:18,949: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 07:22:18,951: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-09 07:22:18,951: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-09 07:22:19,658: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 07:22:19,658: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 07:22:19,660: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-09 07:22:19,660: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-09 09:01:30,585: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 09:01:30,586: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 09:01:30,588: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-09 09:01:30,588: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-09 09:01:31,280: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 09:01:31,280: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 09:01:31,282: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-09 09:01:31,282: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-09 11:34:51,417: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 11:34:51,417: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 11:34:51,419: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-09 11:34:51,419: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-09 11:34:52,124: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 11:34:52,125: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 11:34:52,126: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-09 11:34:52,126: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
DEBUG 2018-03-09 12:41:01,543: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 12:41:01,543: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 12:41:01,545: 	 Error: crab_W3Jets-1 is not a valid CRAB project directory.
ERROR 2018-03-09 12:41:01,545: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-1 is not a valid CRAB project directory.
DEBUG 2018-03-09 12:41:02,268: 	 Executing command: 'resubmit'
DEBUG 2018-03-09 12:41:02,268: 	 Found CRAB cache file /uscms/home/qhuang2/.crab3
ERROR 2018-03-09 12:41:02,270: 	 Error: crab_W3Jets-2 is not a valid CRAB project directory.
ERROR 2018-03-09 12:41:02,270: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1803/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_W3Jets-2 is not a valid CRAB project directory.
